# Generated by Django 4.0.4 on 2022-05-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thing',
            new_name='snacks',
        ),
    ]
