# Generated by Django 4.0.4 on 2022-05-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_thing_snacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='snacks',
            new_name='Snack',
        ),
    ]
